### ISSUE TITLE
Lollipop colorscale

### ISSUE THREAD

**Issue by szabzola** [ftwkoopmans/goat#4]
Hi!
Thanks for the great work!
Using plot_lollipop with score = "oddsratio" the colorscale legend text is still p-value (but showing oddsratio numerical values).
However it can be easily corrected by image editing, the main request is, that the current way x-axis and colorscale is redundant. It would be nice to have eg. p-value on x-axis and oddsratio on color scale, or vice verse, to be more informative.
But in online tool colors of lollipops are up/down effect, which is also a nice option, not available in R version..
Best regards,

**Comment by ftwkoopmans** [comment]
> Using plot_lollipop with score = "oddsratio" the colorscale legend text is still p-value (but showing oddsratio numerical values).

Thanks for reporting, this has been fixed and will be available in the next release.

> the main request is, that the current way x-axis and colorscale is redundant. It would be nice to have eg. p-value on x-axis and oddsratio on color scale, or vice verse, to be more informative. But in online tool colors of lollipops are up/down effect, which is also a nice option, not available in R version.

Good idea. I'll try to implement more flexible controls for the x-axis and color scales in this plot function and add some examples for using it to the function documentation. In general I try try to keep feature parity between both tools where possible, but these things take time because the online tool is implemented in Javascript (i.e. I cannot re-use R code in the online tool, or vice versa). Will ping back here when this is available.

**Comment by ftwkoopmans** [comment]
release 0.9.6 is now available, it should cover all features discussed above, see https://github.com/ftwkoopmans/goat/releases/tag/v0.9.6

you can update the R package using this command;
`pak::pkg_install("ftwkoopmans/goat", upgrade = FALSE) # latter parameter makes us skip optional updates`

Some of the function parameters changed / were renamed btw. Please check the function documentation for `plot_lollipop()` for examples on how you can control values that should be used for x-axis and color-coding.
